myconfig:
  app-name: My Application Name
  app-description: ${myconfig.app-name} is a Spring Boot Application
  admin-first-name: Dan
  admin-last-name: Vega
  adminEmail: danvega@gmail.com
  adminEMail: this props wont be supported , as it's not defined in pojo , if we match name . difference is captial M in this props